"""AEGIS demo API — session-isolated worker financial resilience guidance, plus a
completely separate aggregate-only business/lender API.

All financial records in this MVP are synthetic. The service never asks for or
stores banking credentials; it is decision support, not lending or advice.

Security notes (see also /docs, auto-generated by FastAPI):
- Each worker session token is an unguessable uuid4 and maps to its own isolated
  WorkerFinancialEngine instance — there is no endpoint anywhere that accepts a worker_id
  and returns another session's data. A session is only ever readable with its own token.
- Sessions are pruned after SESSION_TTL_MINUTES of inactivity, and logout invalidates the
  token server-side immediately (not just client-side), so a stale token stops working.
- The business/lender endpoints below use a completely separate credential (X-AEGIS-Business-Key)
  and never read the `sessions` dict — they can only ever reach the synthetic, aggregated
  portfolio in services.portfolio_engine, which has no individual-record endpoint at all.
- Unhandled errors return a generic message, never a stack trace or internal detail.
"""
import os
import time
from typing import List, Optional
from uuid import uuid4

from fastapi import Depends, FastAPI, Header, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field

from services import ml_engine, portfolio_engine
from services.worker_finance import WorkerFinancialEngine

app = FastAPI(title="AEGIS — Worker Financial Resilience", version="5.0.0")
app.add_middleware(CORSMiddleware, allow_origins=["http://localhost:5173", "http://localhost:8443"], allow_credentials=True, allow_methods=["*"], allow_headers=["*"])


@app.exception_handler(Exception)
async def unhandled_exception_handler(request: Request, exc: Exception):
    # Never leak a stack trace or internal detail to the client — the frontend always gets a
    # clean, displayable message and a real HTTP status instead of a blank/broken response.
    return JSONResponse(status_code=500, content={"detail": "Something went wrong on the server. Please try again in a moment."})


SESSION_TTL_MINUTES = 120
sessions: dict[str, WorkerFinancialEngine] = {}
session_last_seen: dict[str, float] = {}
BUSINESS_API_KEY = os.environ.get("AEGIS_BUSINESS_API_KEY", "aegis-demo-lender-key-2026")


def _prune_expired_sessions():
    cutoff = time.time() - SESSION_TTL_MINUTES * 60
    expired = [token for token, seen in session_last_seen.items() if seen < cutoff]
    for token in expired:
        sessions.pop(token, None)
        session_last_seen.pop(token, None)


class Login(BaseModel):
    worker_id: str
    password: str


class Profile(BaseModel):
    worker_id: str = "W001"
    work_type: str = Field(min_length=2, max_length=80)
    operating_area: str = Field(min_length=2, max_length=100)
    income_frequency: str = Field(min_length=2, max_length=30)
    primary_platform: str = Field(min_length=2, max_length=100)
    secondary_income_sources: int = Field(default=0, ge=0, le=10)


class Survey(BaseModel):
    work_type: str
    income_frequency: str
    income_predictability: str
    spending_categories: List[str] = Field(min_length=1)
    essential_monthly_expenses: float = Field(ge=0, le=500000)
    current_savings: float = Field(ge=0, le=5000000)
    emergency_savings: float = Field(ge=0, le=5000000)
    existing_debt: float = Field(ge=0, le=5000000)
    existing_emi: float = Field(ge=0, le=500000)
    financial_goal: str
    desired_savings_goal: float = Field(ge=0, le=5000000)
    borrowing_comfort: str
    financial_concern: str
    income_sources: int = Field(ge=1, le=10)


class BorrowRequest(BaseModel):
    amount: float = Field(ge=1000, le=500000)
    annual_rate_pct: float = Field(ge=0, le=36)
    tenure_months: int = Field(ge=3, le=60)


class Simulation(BaseModel):
    scenario: str = Field(pattern="^(income_decrease_10|income_decrease_30|income_decrease_50|income_increase_10|climate_disruption|unexpected_expense)$")


def session_engine(x_aegis_session: Optional[str] = Header(None)) -> WorkerFinancialEngine:
    if not x_aegis_session or x_aegis_session not in sessions:
        raise HTTPException(status_code=401, detail="Your session has expired or is invalid. Please log in again.")
    session_last_seen[x_aegis_session] = time.time()
    return sessions[x_aegis_session]


def business_auth(x_aegis_business_key: Optional[str] = Header(None)) -> bool:
    if not x_aegis_business_key or x_aegis_business_key != BUSINESS_API_KEY:
        raise HTTPException(status_code=401, detail="A valid business API key is required. See /api/business/demo-key for the demo key.")
    return True


@app.post("/api/auth/login")
def login(body: Login):
    _prune_expired_sessions()
    if body.worker_id.upper() != "W001" or body.password != "demo123":
        raise HTTPException(status_code=401, detail="Invalid demo credentials")
    token = uuid4().hex
    sessions[token] = WorkerFinancialEngine()
    session_last_seen[token] = time.time()
    return {"authenticated": True, "worker_id": "W001", "session": token, "onboarding_complete": False, "data_mode": "SYNTHETIC_DEMO"}


@app.post("/api/auth/logout")
def logout(x_aegis_session: Optional[str] = Header(None)):
    if x_aegis_session:
        sessions.pop(x_aegis_session, None)
        session_last_seen.pop(x_aegis_session, None)
    return {"authenticated": False}


@app.get("/api/health")
def health():
    return {"status": "ok", "service": "AEGIS", "data_mode": "SYNTHETIC_DEMO", "session_isolation": True, "active_sessions": len(sessions)}


@app.get("/api/worker/profile")
def get_profile(engine: WorkerFinancialEngine = Depends(session_engine)):
    return engine.profile


@app.put("/api/worker/profile")
def update_profile(body: Profile, engine: WorkerFinancialEngine = Depends(session_engine)):
    return engine.set_profile(body.model_dump())


@app.get("/api/survey")
def get_survey(engine: WorkerFinancialEngine = Depends(session_engine)):
    return engine.survey


@app.put("/api/survey")
def update_survey(body: Survey, engine: WorkerFinancialEngine = Depends(session_engine)):
    engine.set_survey(body.model_dump())
    return engine.analysis()


@app.get("/api/financial/data")
def financial_data(engine: WorkerFinancialEngine = Depends(session_engine)):
    return {"transactions": engine.transactions, "weekly_income": engine.weekly_income(), "provenance": "SYNTHETIC / DEMO", "credentials_collected": False}


@app.get("/api/decision")
def decision(engine: WorkerFinancialEngine = Depends(session_engine)):
    return engine.analysis()


@app.get("/api/models")
def models(engine: WorkerFinancialEngine = Depends(session_engine)):
    return engine.models()


@app.get("/api/alerts")
def alerts(engine: WorkerFinancialEngine = Depends(session_engine)):
    return {"alerts": engine.latest_alerts()}


@app.get("/api/climate/72h")
def climate(engine: WorkerFinancialEngine = Depends(session_engine)):
    return engine.climate()


@app.post("/api/borrowing")
def borrowing(body: BorrowRequest, engine: WorkerFinancialEngine = Depends(session_engine)):
    return engine.borrowing(body.model_dump())


@app.post("/api/simulation")
def simulation(body: Simulation, engine: WorkerFinancialEngine = Depends(session_engine)):
    return engine.simulate(body.scenario)


@app.post("/api/consent/grant")
def grant_consent(engine: WorkerFinancialEngine = Depends(session_engine)):
    return engine.grant_consent()


@app.post("/api/consent/revoke")
def revoke_consent(engine: WorkerFinancialEngine = Depends(session_engine)):
    return engine.revoke_consent()


@app.get("/api/consent")
def consent(engine: WorkerFinancialEngine = Depends(session_engine)):
    return engine.consent_status()


@app.delete("/api/financial/data")
def clear_data(engine: WorkerFinancialEngine = Depends(session_engine)):
    return engine.clear_data()


# --- Business / lender API — entirely separate auth realm from worker sessions above. ---
# These endpoints never read `sessions`, never accept a worker_id, and never return an
# individual record — only portfolio-wide aggregates from services.portfolio_engine.

@app.get("/api/business/demo-key")
def business_demo_key():
    """Public on purpose, exactly like the worker demo credentials in the README — this is a
    judge-facing demo, not a real credential. A production deployment would remove this endpoint."""
    return {"demo_api_key": BUSINESS_API_KEY, "header": "X-AEGIS-Business-Key", "note": "Demo key only. Grants access to aggregated portfolio analytics — never any individual worker's data."}


@app.get("/api/business/portfolio-summary")
def business_portfolio_summary(_: bool = Depends(business_auth)):
    return portfolio_engine.portfolio_summary()


@app.get("/api/business/model-info")
def business_model_info(_: bool = Depends(business_auth)):
    return ml_engine.model_info()
